version: '3.8'
services:
    fastapi:
        build: ./inretensys-fastapi/
        container_name: gui_fastapi
        expose:
            - 8001
        ports:
            - "8001:8001"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./inretensys-fastapi/api:/app/api
            - /home/pyrokar/scratch4:/app/working
        command: ["python", "-m", "uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8001"]
        networks:
            - network_intern
    db:
        image: 'postgres:latest'        
        container_name: gui_db
        restart: always
        expose:
            - 5432
        env_file:
            - ./inretensys-gui/.envs/db.postgres
        volumes:
            - ./db-data/:/var/lib/postgresql/data/
        networks:
            - network_intern
    app:
        build:
            context: ./inretensys-gui/app
            dockerfile: ./compose/production/app_postgres/Dockerfile
        container_name: gui_app
        restart: always
        env_file:
            - ./inretensys-gui/.envs/epa.postgres
        expose:
            - 8000
        volumes:
            - static_volume:/src/cdn_static_root
        command: "python manage.py runserver 0.0.0.0:8000"
        networks:
            - network_intern
    nginx:
        image: nginx:1.21-alpine
        container_name: gui_ngx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./inretensys-gui/nginx/postgres:/etc/nginx/conf.d
            - static_volume:/static
        depends_on:
            - app
        networks:
            - network_intern
    pgadmin:
        image: dpage/pgadmin4

        container_name: pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
        networks:
            - network_intern

volumes:
    db_data:
    static_volume:

networks:
    network_intern:
