version: '3.8'
services:
    fastapi:
        build: ./services/fastapi/
        container_name: ensys_fastapi
        env_file:
            - ./services/fastapi/.env
        ports:
            - "${FASTAPI_PORT}:8001"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${LOCAL_WORKDIR}:/app/working
        networks:
            - network_intern
    app:
        build:
            context: ./services/gui/app
            dockerfile: ./dockerfile
        container_name: ensys_app
        restart: always
        env_file:
            - ./.env
        volumes:
            - static_volume:/src/cdn_static_root
            - ${LOCAL_WORKDIR}:/src/dumps
        depends_on:
            - fastapi
        networks:
            - network_intern
networks:
    network_intern:

volumes:
  static_volume:
  pgadmin_volume: